spring.application.name=feastflow-app

# MongoDB connection URI (override with env var MONGODB_URI)
spring.data.mongodb.uri=mongodb+srv://dhruvesh:dhruv%402150@cluster0.gdtzqq8.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=feastflow

